package render

import (
	"fmt"
	"html"
	"io"
	"strings"
	"time"

	"github-star-sync/internal/model"
)

// Markdown writes a Chinese, TOC-friendly STARRED.md.
func Markdown(w io.Writer, r model.Report) error {
	var b strings.Builder
	b.WriteString("<!-- generated by github-star-sync; do not edit -->\n\n")
	b.WriteString("# ")
	b.WriteString(r.Title)
	b.WriteString("\n\n")
	b.WriteString(fmt.Sprintf(
		"> 自动生成 · %s · %d 个账号 · 共 **%d** 个星标\n\n",
		r.Generated.Local().Format("2006-01-02 15:04"),
		len(r.Users),
		r.Total,
	))

	b.WriteString("## 目录\n\n")
	for _, u := range r.Users {
		userAnchor := anchorID("user-" + u.Username)
		title := userSectionTitle(u)
		if u.Err != "" {
			b.WriteString(fmt.Sprintf("- [%s](#%s)（获取失败）\n", title, userAnchor))
			continue
		}
		b.WriteString(fmt.Sprintf("- [%s](#%s)（%d）\n", title, userAnchor, u.Total))
		for _, c := range u.Categories {
			b.WriteString(fmt.Sprintf("  - [%s](#%s)（%d）\n",
				c.Name, anchorID(u.Username+"-"+c.Name), len(c.Repos)))
		}
	}
	b.WriteString("\n---\n\n")

	for _, u := range r.Users {
		userAnchor := anchorID("user-" + u.Username)
		b.WriteString(fmt.Sprintf("## %s\n\n", userSectionTitle(u)))
		b.WriteString(fmt.Sprintf("<a id=\"%s\"></a>\n\n", userAnchor))
		if u.Err != "" {
			b.WriteString(fmt.Sprintf("> ⚠️ 获取失败：%s\n\n", u.Err))
			continue
		}
		if u.Total == 0 {
			b.WriteString("_暂无公开星标_\n\n")
			continue
		}
		for _, c := range u.Categories {
			b.WriteString(fmt.Sprintf("### %s\n\n", c.Name))
			b.WriteString(fmt.Sprintf("<a id=\"%s\"></a>\n\n", anchorID(u.Username+"-"+c.Name)))
			b.WriteString("| 仓库 | 简介 | 语言 | ★ |\n")
			b.WriteString("| --- | --- | --- | ---: |\n")
			for _, repo := range c.Repos {
				name := repo.FullName
				if repo.Archived {
					name += " ⌁"
				}
				desc := escapeMDCell(repo.Description)
				lang := repo.Language
				if lang == "" {
					lang = "—"
				}
				b.WriteString(fmt.Sprintf("| [%s](%s) | %s | %s | %s |\n",
					escapeMDCell(name), repo.HTMLURL, desc, escapeMDCell(lang), formatStars(repo.Stars)))
			}
			b.WriteString("\n")
		}
	}

	_, err := io.WriteString(w, b.String())
	return err
}

func userSectionTitle(u model.UserStars) string {
	if u.Label != "" && u.Label != "@"+u.Username {
		return fmt.Sprintf("%s · @%s", u.Label, u.Username)
	}
	return "@" + u.Username
}

func escapeMDCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

func formatStars(n int) string {
	if n >= 1000 {
		return fmt.Sprintf("%.1fk", float64(n)/1000)
	}
	return fmt.Sprintf("%d", n)
}

func anchorID(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-', r == '_':
			b.WriteRune(r)
		case r == ' ', r == '/', r == '.':
			b.WriteByte('-')
		default:
			// keep CJK and others as hex for stable anchors in MD/HTML
			b.WriteString(fmt.Sprintf("%x", r))
		}
	}
	out := b.String()
	if out == "" {
		return "section"
	}
	return out
}

// HTML writes a single-file modern Chinese page with client-side search.
func HTML(w io.Writer, r model.Report) error {
	var b strings.Builder
	b.WriteString("<!DOCTYPE html>\n<html lang=\"zh-CN\">\n<head>\n")
	b.WriteString("<meta charset=\"utf-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	b.WriteString("<title>")
	b.WriteString(html.EscapeString(r.Title))
	b.WriteString("</title>\n<style>\n")
	b.WriteString(htmlCSS)
	b.WriteString("\n</style>\n</head>\n<body>\n")

	b.WriteString("<div class=\"page\">\n")
	b.WriteString("<header class=\"hero\">\n")
	b.WriteString("<p class=\"eyebrow\">GitHub Stars</p>\n")
	b.WriteString("<h1>")
	b.WriteString(html.EscapeString(r.Title))
	b.WriteString("</h1>\n")
	b.WriteString(fmt.Sprintf(
		"<p class=\"meta\">自动生成 · %s · %d 个账号 · 共 <strong>%d</strong> 个星标</p>\n",
		html.EscapeString(r.Generated.Local().Format("2006-01-02 15:04")),
		len(r.Users),
		r.Total,
	))
	b.WriteString(`<div class="search-wrap"><input id="q" type="search" placeholder="搜索仓库名或简介…" autocomplete="off"></div>`)
	b.WriteString("\n</header>\n")

	b.WriteString("<div class=\"layout\">\n")
	b.WriteString("<nav class=\"toc\" aria-label=\"目录\">\n<strong>目录</strong>\n<ul>\n")
	for _, u := range r.Users {
		uid := anchorID("user-" + u.Username)
		title := userSectionTitle(u)
		if u.Err != "" {
			b.WriteString(fmt.Sprintf("<li><a href=\"#%s\">%s</a> <span class=\"muted\">失败</span></li>\n",
				uid, html.EscapeString(title)))
			continue
		}
		b.WriteString(fmt.Sprintf("<li><a href=\"#%s\">%s</a> <span class=\"count\">%d</span>\n<ul>\n",
			uid, html.EscapeString(title), u.Total))
		for _, c := range u.Categories {
			cid := anchorID(u.Username + "-" + c.Name)
			b.WriteString(fmt.Sprintf("<li><a href=\"#%s\">%s</a> <span class=\"count\">%d</span></li>\n",
				cid, html.EscapeString(c.Name), len(c.Repos)))
		}
		b.WriteString("</ul></li>\n")
	}
	b.WriteString("</ul>\n</nav>\n")

	b.WriteString("<main>\n")
	for _, u := range r.Users {
		uid := anchorID("user-" + u.Username)
		b.WriteString(fmt.Sprintf("<section class=\"user\" id=\"%s\">\n", uid))
		b.WriteString("<h2>")
		b.WriteString(html.EscapeString(userSectionTitle(u)))
		b.WriteString("</h2>\n")
		if u.Err != "" {
			b.WriteString("<p class=\"error\">获取失败：")
			b.WriteString(html.EscapeString(u.Err))
			b.WriteString("</p>\n</section>\n")
			continue
		}
		if u.Total == 0 {
			b.WriteString("<p class=\"muted\">暂无公开星标</p>\n</section>\n")
			continue
		}
		for _, c := range u.Categories {
			cid := anchorID(u.Username + "-" + c.Name)
			b.WriteString(fmt.Sprintf("<section class=\"cat\" id=\"%s\">\n", cid))
			b.WriteString("<h3>")
			b.WriteString(html.EscapeString(c.Name))
			b.WriteString(fmt.Sprintf(" <span class=\"count\">%d</span></h3>\n", len(c.Repos)))
			b.WriteString("<div class=\"grid\">\n")
			for _, repo := range c.Repos {
				archived := ""
				if repo.Archived {
					archived = ` data-archived="1"`
				}
				lang := repo.Language
				if lang == "" {
					lang = "—"
				}
				hay := strings.ToLower(repo.FullName + " " + repo.Description + " " + lang)
				b.WriteString(fmt.Sprintf(
					`<article class="card" data-q="%s"%s>`,
					html.EscapeString(hay), archived,
				))
				b.WriteString(fmt.Sprintf(`<a class="name" href="%s" target="_blank" rel="noopener">%s</a>`,
					html.EscapeString(repo.HTMLURL), html.EscapeString(repo.FullName)))
				if repo.Archived {
					b.WriteString(`<span class="badge">已归档</span>`)
				}
				if repo.Description != "" {
					b.WriteString(fmt.Sprintf(`<p class="desc">%s</p>`, html.EscapeString(repo.Description)))
				}
				b.WriteString(`<div class="foot">`)
				b.WriteString(fmt.Sprintf(`<span class="lang">%s</span>`, html.EscapeString(lang)))
				b.WriteString(fmt.Sprintf(`<span class="stars">★ %s</span>`, formatStars(repo.Stars)))
				b.WriteString(`</div></article>`)
				b.WriteByte('\n')
			}
			b.WriteString("</div>\n</section>\n")
		}
		b.WriteString("</section>\n")
	}
	b.WriteString("</main>\n</div>\n")
	b.WriteString(fmt.Sprintf("<footer><p>generated by github-star-sync · %s</p></footer>\n",
		html.EscapeString(r.Generated.UTC().Format(time.RFC3339))))
	b.WriteString("</div>\n")
	b.WriteString(htmlJS)
	b.WriteString("\n</body>\n</html>\n")
	_, err := io.WriteString(w, b.String())
	return err
}

const htmlCSS = `:root {
  --bg: #f6f3ee;
  --ink: #1c1917;
  --muted: #78716c;
  --card: #fffcf7;
  --line: #e7e0d6;
  --accent: #0f766e;
  --accent-soft: #ccfbf1;
  --shadow: 0 10px 30px rgba(28, 25, 23, .06);
  --radius: 14px;
  --font: "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif;
}
* { box-sizing: border-box; }
html { scroll-behavior: smooth; }
body {
  margin: 0;
  font-family: var(--font);
  color: var(--ink);
  background:
    radial-gradient(1200px 600px at 10% -10%, #d9f3ef 0%, transparent 55%),
    radial-gradient(900px 500px at 100% 0%, #fde68a55 0%, transparent 50%),
    var(--bg);
  line-height: 1.55;
}
.page { max-width: 1180px; margin: 0 auto; padding: 32px 20px 64px; }
.hero { margin-bottom: 28px; }
.eyebrow {
  margin: 0 0 8px;
  text-transform: uppercase;
  letter-spacing: .12em;
  font-size: 12px;
  color: var(--accent);
  font-weight: 700;
}
h1 { margin: 0 0 8px; font-size: clamp(1.8rem, 3vw, 2.4rem); letter-spacing: -.02em; }
.meta { margin: 0 0 18px; color: var(--muted); }
.search-wrap input {
  width: min(480px, 100%);
  border: 1px solid var(--line);
  background: var(--card);
  border-radius: 999px;
  padding: 12px 18px;
  font: inherit;
  box-shadow: var(--shadow);
  outline: none;
}
.search-wrap input:focus { border-color: var(--accent); }
.layout { display: grid; grid-template-columns: 240px 1fr; gap: 28px; align-items: start; }
.toc {
  position: sticky; top: 16px;
  background: color-mix(in srgb, var(--card) 92%, white);
  border: 1px solid var(--line);
  border-radius: var(--radius);
  padding: 16px;
  max-height: calc(100vh - 32px);
  overflow: auto;
  box-shadow: var(--shadow);
  scrollbar-width: none;
  -ms-overflow-style: none;
}
.toc::-webkit-scrollbar { display: none; }
.toc strong { display: block; margin-bottom: 8px; }
.toc ul { list-style: none; margin: 0; padding: 0; }
.toc li { margin: 6px 0; }
.toc ul ul { padding-left: 12px; margin-top: 4px; }
.toc a { color: inherit; text-decoration: none; }
.toc a:hover { color: var(--accent); }
.count { color: var(--muted); font-size: 12px; }
.muted { color: var(--muted); }
.error { color: #b91c1c; background: #fef2f2; padding: 10px 12px; border-radius: 10px; }
.user { margin-bottom: 36px; }
.user > h2 {
  margin: 0 0 16px;
  padding-bottom: 8px;
  border-bottom: 1px solid var(--line);
  font-size: 1.45rem;
}
.cat { margin: 0 0 22px; }
.cat h3 { margin: 0 0 12px; font-size: 1.05rem; }
.grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
  gap: 12px;
}
.card {
  background: var(--card);
  border: 1px solid var(--line);
  border-radius: var(--radius);
  padding: 14px 14px 12px;
  box-shadow: var(--shadow);
  display: flex;
  flex-direction: column;
  gap: 8px;
  min-height: 118px;
}
.card[data-archived="1"] { opacity: .72; }
.card.hidden { display: none; }
.name {
  color: var(--ink);
  font-weight: 650;
  text-decoration: none;
  word-break: break-all;
}
.name:hover { color: var(--accent); }
.badge {
  align-self: start;
  font-size: 11px;
  padding: 2px 8px;
  border-radius: 999px;
  background: var(--accent-soft);
  color: var(--accent);
}
.desc {
  margin: 0;
  color: var(--muted);
  font-size: 13px;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  flex: 1;
}
.foot {
  display: flex;
  justify-content: space-between;
  gap: 8px;
  font-size: 12px;
  color: var(--muted);
}
.lang {
  background: #f5f5f4;
  border-radius: 999px;
  padding: 2px 8px;
}
footer { margin-top: 40px; color: var(--muted); font-size: 12px; }
@media (max-width: 860px) {
  .layout { grid-template-columns: 1fr; }
  .toc { position: static; max-height: none; }
}`

const htmlJS = `<script>
(() => {
  const q = document.getElementById('q');
  if (!q) return;
  const cards = [...document.querySelectorAll('.card')];
  q.addEventListener('input', () => {
    const v = q.value.trim().toLowerCase();
    cards.forEach(c => {
      const hay = c.getAttribute('data-q') || '';
      c.classList.toggle('hidden', v !== '' && !hay.includes(v));
    });
  });
})();
</script>`
